---
- hosts: all

  become: true

  tasks:
          - name: Check OS Version
            command: lsb_release -a
            register: os-version
          - name: Print OS Version
            debug:
                 msg: "{{ os-version.stdout_lines }}"
