---
- hosts: all

  become: true

  tasks:
          - name: Check OS Version
            command: lsb_release -d
            register: version
          - name: Print OS Version
            debug:
                 msg: "{{ version.stdout_lines }}"
